import type { Metadata } from "next";
import "./globals.css";
import { cursive, dm_sans, space, strech, tall, unbounded } from "@/utils/fonts";
import { CursorProvider } from "@/elements/CursorContext";
import CustomCursor from "@/elements/Cursor";


export const metadata: Metadata = {
  title: "Arinova Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans.className} ${space.variable} ${strech.variable} ${unbounded.variable} ${tall.variable} ${cursive.variable} antialiased cursor-none`}
      >
        <CursorProvider>
        {children}
        <CustomCursor />
        </CursorProvider>
      </body>
    </html>
  );
}
